name: developer_toolbox

services:
  emulator:
    container_name: "emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:${SbusEmulatorConfigPath}"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}" # Password should be same as what is set for SQL Edge  
      ACCEPT_EULA: ${ACCEPT_EULA}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL} # Optional: Time in seconds to wait for SQL to be ready (default is 15 seconds)
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
      back_net:
    cpus: "1"
    mem_limit: "516MB"

  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16 

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5    
    networks:
      - back_net
    cpus: 1
    mem_limit: "256MB"

  backend:
    container_name: backend
    image: ghcr.io/blogdoft/developer-toolbox/developer-toolbox-api:latest
    env_file:
      - .env
      - backend.env
    volumes:
      - "${CONFIG_PATH}:${SbusEmulatorConfigPath}"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
      back_net:
    depends_on:
      emulator:
        condition: service_started
      postgres:
        condition: service_healthy
    cpus: "1"
    mem_limit: "256MB"      

  frontend:
    image: ghcr.io/blogdoft/developer-toolbox/developer-toolbox-client:latest
    networks:
      - front_net
      - back_net
    depends_on:
      - backend
    cpus: "1"
    mem_limit: "128MB"         

  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    container_name: reverse-proxy
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
      back_net:
      front_net:
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
    mem_limit: 128m
    cpus: 0.5

networks:
  sb-emulator:
  back_net:
    driver: bridge
  front_net:
    driver: bridge